### ISSUE TITLE
Which UF2 file?

### ISSUE THREAD

**Issue by probablypablito** [polhenarejos/pico-fido#1]
Hey! This project is super interesting to me. I wanted to set it up, but I'm not sure which uf2 file to download. Are there instructions on how to choose the right one?

**Comment by polhenarejos** [comment]
It depends on the Pico board you have. There're lots of different boards from multiple vendors.

In case you have the original one sold by the RPi Foundation, you must download `pico_fido_pico-X.Y.uf2`. Put the board into loading mode (press bootsel button and plug it on) and copy the uf2 file to the mounted unit.
