### ISSUE TITLE
OTP static key limited to 8 characters instead of 32 on pico

### ISSUE THREAD

**Issue by niansa** [polhenarejos/pico-fido#14]
```
$ ykman otp static 1 DrHfEHtICeCeNuEjkfHJdCGuvbhEhGvDenecgk
Slot 1 is already configured. Overwrite configuration? [y/N]: y
```
Stored password ends up being: `DrHfEHtI`

**Comment by polhenarejos** [comment]
Did you try it with a legit Yubikey? It seems that YKMAN supports 16 bytes for static OTP (if you have 8 might be caused by SHORT_TICKET flag).

BTW it can be increased easily.

**Comment by polhenarejos** [comment]
From Yubico documentation, static passwords are 16 bytes length:

https://docs.yubico.com/yesdk/users-manual/application-otp/commands-configure-slot.html

However, Yubico Manager uses 38 bytes length. Perhaps doc is outdated.

**Comment by niansa** [comment]
But then why can it only be 8, not 16?

**Comment by polhenarejos** [comment]
Not really. In version 5.8 we removed that limitation and Pico Fido is able to send up to 38 bytes.
