### ISSUE TITLE
Can't use it to passwordless login to Google

### ISSUE THREAD

**Issue by Le55mmore** [polhenarejos/pico-fido#20]
I flashed last firmware to generic rp2040 and it works for 2fa when i need to enter my password and press a button, but every time i try to setup passwordless login, it asks and sets pin, and send credentials, everything seems fine, but when i try to login using passwordless method it accepts pin as correct but seems not find credentials, don't ask to press button and asks for different key. When i try to do same in yubikey playground it works perfectly.
![image](https://github.com/polhenarejos/pico-fido/assets/104894820/30ae5943-7fab-4bf3-adb3-299d471f0d3e)
![image](https://github.com/polhenarejos/pico-fido/assets/104894820/5ef0bf61-9a64-46aa-a492-f9cf5054f5ef)
![image](https://github.com/polhenarejos/pico-fido/assets/104894820/bbe4a9cb-1844-47fc-a868-e75ed6d540ca)
I just don't get it. Should it work?

**Comment by polhenarejos** [comment]
Which browser are you using?
Can you try with www.webauthn.io?

**Comment by Le55mmore** [comment]
I use brave(chromium)
https://webauthn.io/ works fine, i also checked github it works too.
When i removed token for password+button from google and now it does not request pin and just waiting for something
![image](https://github.com/polhenarejos/pico-fido/assets/104894820/37afdf70-25ac-402d-aed8-3364c2cbfb03)
![image](https://github.com/polhenarejos/pico-fido/assets/104894820/fa1201f4-4cd4-4438-b081-7567d0e9c5e8)
same in chrome, edge. Firefox asks for button press first, then asks for pin and tells to use different key device.

**Comment by aleytus** [comment]
@Le55mmore В настройках безопасности гугла выбери пункт "Ключи доступа" - "Создать ключ доступа" - "Использовать другое устройство"

PS. Использую последний фаерфокс и ltsb сборку 10 винды
Свой собственный сертификат и VID/PID (FEFF:FCFD)
![изображение](https://github.com/polhenarejos/pico-fido/assets/41133651/2acecc6e-5c33-4661-a23a-a640115c8d32)
![изображение](https://github.com/polhenarejos/pico-fido/assets/41133651/9bf16b00-3bfc-4ac6-9df2-0d991e7f1acf)

**Comment by Le55mmore** [comment]
I nuked flash and updated to 5.8, passwordless works now everywhere. Cool
