### ISSUE TITLE
Can't use pico-fido-tool.py

### ISSUE THREAD

**Issue by M11158002** [polhenarejos/pico-fido#21]
I'm getting the error "ImportError: cannot import name 'windows' from 'secure_key' (unknown location)" while using pico-fido-tool.py
Execution environment:
Git Branch: main
System Version: Ubuntu 22.04.3 LTS
Architecture: amd64
Python Version:3.11.6
Python Package:
fido2:1.1.2
cryptography:41.0.5

**Comment by polhenarejos** [comment]
It is not implemented yet. What do you need from pico-fido-tool.py?

**Comment by polhenarejos** [comment]
Fixed in 3652368. Reopen if problems still persist.
