### ISSUE TITLE
Pico patcher website seems unresponsive

### ISSUE THREAD

**Issue by sylvainpelissier** [polhenarejos/pico-fido#25]
After uploading an image on https://www.picokeys.com/pico-patcher/ the website display a message: "Thanks for contacting us! We will be in touch with you shortly." but the new image is never downloaded.

**Comment by polhenarejos** [comment]
Something has been broken in last update. We'll fix soon.

**Comment by polhenarejos** [comment]
Fixed in the website. Thanks for reporting.
