### ISSUE TITLE
pico screen

### ISSUE THREAD

**Issue by adminy** [polhenarejos/pico-fido#32]
I'm wondering of making use of screen and maybe a button which allows to flip between all the stored credentials or maybe a password fill. Not sure how hard this feature would be to add.

**Comment by polhenarejos** [comment]
If you mean using 2 slots like in a Yubikey, BOOTSEL button can be pressed once or twice for selecting slot 1 or 2.

**Comment by polhenarejos** [comment]
Closed due to inactivity.
