### ISSUE TITLE
Nitrokey 3 secrets list name display error

### ISSUE THREAD

**Issue by zvrh** [polhenarejos/pico-fido#33]
## secrets list name display error：

![QQ截图20231212105415](https://github.com/polhenarejos/pico-fido/assets/16538800/13038ec8-f5d1-4976-b232-f85b90605c44)

## after the following modification, it will work normally：

https://github.com/polhenarejos/pico-fido/blob/7e2ecdbc5659fb4de39b848503d759e39d85d573/src/fido/oath.c#L290-L293

![QQ截图20231212113033](https://github.com/polhenarejos/pico-fido/assets/16538800/f6e00c2d-e1e3-463e-9cd6-716de3be4972)

**Comment by polhenarejos** [comment]
Hi. Do you know why is that? If we apply your modification, probably it won't work with Yubikey. Perhaps is a bug with `nitropy` app?

**Comment by zvrh** [comment]
I don't quite understand this issue either. As you said, maybe this is a problem with Nitrokey APP.
