### ISSUE TITLE
Fail to open otp on windows client

### ISSUE THREAD

**Issue by agczsz** [polhenarejos/pico-fido#38]
Fail to open otp on windows client，it can only use on my phone

**Comment by polhenarejos** [comment]
More details needed:
- OS
- Client software
- FIDO version
- Error message

**Comment by agczsz** [comment]
waveshare-rp2040-one,windows,totp
![image](https://github.com/polhenarejos/pico-fido/assets/121206519/c7114a58-fc48-4fb4-b64a-12e428ecfb53)
other function is okey
![image](https://github.com/polhenarejos/pico-fido/assets/121206519/3d165dc9-6c60-4433-810f-f4f081e39ff4)
and totp works well on android with otg

**Comment by fucksophie** [comment]
TOTP works fine on Linux. Latest (as of posting) yubico authenicator, on
```
╭──────────────────┬────────────────────────────────────────────────────────────╮
│ kernel-name      │ Linux                                                      │
│ nodename         │ constellation                                              │
│ kernel-release   │ 6.8.8-zen1-1-zen                                           │
│ kernel-version   │ #1 ZEN SMP PREEMPT_DYNAMIC Sun, 28 Apr 2024 15:59:30 +0000 │
│ machine          │ x86_64                                                     │
│ operating-system │ GNU/Linux                                                  │
╰──────────────────┴────────────────────────────────────────────────────────────╯
```

**Comment by polhenarejos** [comment]
v5.10 introduced some bugfixes for Windows. Reopen if it still persists.
