### ISSUE TITLE
Help Needed setting up a Raspberry Pi Pico RP2040 

### ISSUE THREAD

**Issue by ryanamaral** [polhenarejos/pico-fido#5]
Thanks for making this library open-source 🚀 

I would like to start using it on my Raspberry Pi Pico RP2040 but I need some help identifying what I'm doing wrong.

Steps I've taken:
1. I started by flashing my pico with the existing build `pico_fido_pico-2.8.uf2`
2. The led starts blinking
3. When I then start the registration process the LED goes off 
4. When I click the button nothing happens

I've tried at https://www.token2.com/tools/fido2-test/ and https://demo.yubico.com/webauthn-technical/registration

Screenshots
![1](https://user-images.githubusercontent.com/3763228/219600546-e928cd6f-85a2-4720-bab5-39646a39a3ba.png)
![2](https://user-images.githubusercontent.com/3763228/219600571-de540a8d-321e-4c07-a210-27f53f316ef4.png)
![3](https://user-images.githubusercontent.com/3763228/219600574-654cd729-029c-427b-95fb-6bb40be2d532.png)

**Comment by polhenarejos** [comment]
If the LED goes off permanently it means it crashed for some reason. 

Which Pico model you use? Note the file you downloaded is just for the Pico model manufactured by the Raspberry Foundation https://www.raspberrypi.com/products/raspberry-pi-pico/
Have you nuked first? It is necessary to blank flash memory first. https://github.com/polhenarejos/pico-nuke
Can you try with the newest release 2.10? It fixes lots of bugs and could be related with yours.
I usually use https://webauthn.io/ for testing.

**Comment by ryanamaral** [comment]
> Which Pico model you use? Note the file you downloaded is just for the Pico model manufactured by the Raspberry Foundation

That's exactly the one I'm using here.

> Have you nuked first? It is necessary to blank flash memory first.

Not really, didn't know that was a step until you made me aware.

> Can you try with the newest release 2.10? It fixes lots of bugs and could be related with yours.

Sure, I've followed the steps you've provided, nuked it first, and then flashed the latest version 2.10, and it is working! 

>  I usually use https://webauthn.io/ for testing.

Looks good, thanks. I'm using that one from now on.

Thanks for your help 🙇‍♂️
