### ISSUE TITLE
www.picokeys.com is down

### ISSUE THREAD

**Issue by rojvv** [polhenarejos/pico-fido#56]

**Comment by polhenarejos** [comment]
I do not observe any problem.

**Comment by rojvv** [comment]
This is what Cloudflare says.

![telegram-cloud-photo-size-2-5348125128912921181-y](https://github.com/user-attachments/assets/14038b05-816e-493a-830e-25c45d601cc6)

**Comment by rojvv** [comment]
And sometimes it just never loads.

<img width="716" alt="Screenshot 2024-08-21 at 22 36 11" src="https://github.com/user-attachments/assets/08ada768-bea4-4b89-b043-b125029dde48">

Connection times out.

<img width="861" alt="Screenshot 2024-08-21 at 22 37 07" src="https://github.com/user-attachments/assets/84167665-bc58-4487-8d36-5a804394a2e6">

**Comment by rojvv** [comment]
And here is how making a request with curl looks like.

![telegram-cloud-document-2-5348125128456688630](https://github.com/user-attachments/assets/bbf6ce80-cd77-4518-a260-1ce1a8869e82)

**Comment by rojvv** [comment]
Everything is alright now.
