### ISSUE TITLE
Attestation Error - Tested on Raspberry Pi Pico RP2040

### ISSUE THREAD

**Issue by ryanamaral** [polhenarejos/pico-fido#6]
I've tested at `https://webauthn.io/` the **attestation direct** setting and seems to be an issue with the counter, as the error message seems to indicate. 

| 1# Register | 2# Authenticate | 3# Choose a passkey | 
| :---: | :---: | :---: |
| ![att_register](https://user-images.githubusercontent.com/3763228/219856066-9724da62-c462-4b68-90aa-7f9bfff361b6.png) | ![att_auth](https://user-images.githubusercontent.com/3763228/219856070-c644c346-cbf5-44be-9fe9-a8b35e0ee58e.png) | ![att_auth_chooser_dialog](https://user-images.githubusercontent.com/3763228/219856073-e5495813-1363-48fe-9083-3d75e0ee5fa9.png) |

1. There are no issues in the 1# screenshot.
2. When authenticating right after registering I always see the count error message (2# screenshot).
3. However, it works (sometimes) when I try to authenticate the same user later after registering more users.
4. The error authenticating in the 3# screenshot happens sometimes, couldn't find a pattern on this one yet.

Tested on: Raspberry Pi Pico RP2040

Let me know if you need more details.

Keep up the great work, thanks! 🚀

**Comment by polhenarejos** [comment]
Confirmed. Attestation seems irrelevant, as it also happens with default parameters. After consecutive authentication it works.
