### ISSUE TITLE
pico patcher tool doesn't work with 5.12

### ISSUE THREAD

**Issue by dragonnn** [polhenarejos/pico-fido#64]
If I upload 5.10 file for my waveshare one it works fine, file is downloaded.
When I select 5.12 file and press nothing happens.
I also tried running local the [pico-fido-patch-vidpid.sh](https://github.com/polhenarejos/pico-fido/blob/main/pico-fido-patch-vidpid.sh), it seam like it run fine but when I flashed the generated uf2 to my waveshare one it didn't show up with the right VID:PID I put to that script.
Any idea?

**Comment by dragonnn** [comment]
I did mean the web page pico patcher, this one: https://www.picokeys.com/pico-patcher/ doesn't work for me with 5.12. Tried with both Vivaldi and Firefox to rule out a web browser issue (and it works fine with 5.10).

**Comment by polhenarejos** [comment]
Which VIDPID do you use?

**Comment by dragonnn** [comment]
I tested some custom ones and a few presets (mostly interested in the Yubikey ones). 
![image](https://github.com/user-attachments/assets/35c4740d-8454-4a58-be53-00b26839693f)
Here is how it looks on my PC, I press PATCH in this state and nothing happens. If I select pico_fido_waveshare_rp2040_one-5.10.uf2 I get a patched file on that same page.

**Comment by polhenarejos** [comment]
Interestingly only happens with ` pico_fido_waveshare_rp2040_one-5.12.uf2`

**Comment by dragonnn** [comment]
At least it is reproducible :D

**Comment by polhenarejos** [comment]
Can you try this release? https://github.com/polhenarejos/pico-fido/releases/tag/nightly-development

**Comment by dragonnn** [comment]
That worked, thanks!
