### ISSUE TITLE
Support for VCC-GND YD-2040

### ISSUE THREAD

**Issue by hashashin** [polhenarejos/pico-fido#66]
Please add support for this chinese board, thanks!

https://github.com/initdc/YD-RP2040

**Comment by polhenarejos** [comment]
Support for 3rd-party boards is given by Raspberry Foundation within de Pico SDK. https://github.com/raspberrypi/pico-sdk

If your board is not listed in  https://github.com/raspberrypi/pico-sdk/tree/master/src/boards/include/boards it will not be possible to build it. 

In any case, if your board is similar to a preexisting one you can use the same firmware (specially if both use same GPIO and flash size).
