### ISSUE TITLE
Add support for working like 'FIPS YubiKeys'

### ISSUE THREAD

**Issue by kholia** [polhenarejos/pico-fido#75]
https://www.yubico.com/products/yubikey-fips/ are different from regular YubiKey(s).

Some environments only accept these 'FIPS YubiKey(s)'.

Thanks!

**Comment by polhenarejos** [comment]
What do you mean by "adding support"? FIPS devices are more restrictive and limited, as they contain secure measures oriented to obtain a certification, which is not the scope of Pico Keys.

**Comment by kholia** [comment]
Yes, Pico Keys may not gets FIPS certification but can the underlying `secure measures` be implemented to achieve unofficial compatibility / interoperability?

I don't know the inner working of these keys (yet) so please feel free to close this feature request.

Thank you!

**Comment by jay0lee** [comment]
There'd be little point to unofficial FIPS support, it's either FIPS certified or it's not. Certification is a multi step process that involves 3p vendor review (read that as $$$).
