### ISSUE TITLE
I lost access to my account in 2 acts

### ISSUE THREAD

**Issue by aleytus** [polhenarejos/pico-fido#8]
- **I use 2 factor authorization**

> ![1](https://github.com/polhenarejos/pico-fido/assets/41133651/a92c7e29-7315-46af-9d4b-c133e4642de6)

- **Google recently added support for WebAuthn
So I decided to connect it
Then I deleted the key and rebinded it to add support for WebAuthn**

> ![2](https://github.com/polhenarejos/pico-fido/assets/41133651/db3e360b-5ccf-488b-a384-2faea7d770a9)

- **And after that. I can't get into my account...**

> ![3](https://github.com/polhenarejos/pico-fido/assets/41133651/4f4a3dc7-e137-46f0-bb5e-10ecaf7746c5)

- **The 2-factor authorization also does not work**

> ![4](https://github.com/polhenarejos/pico-fido/assets/41133651/1726c357-e949-4aa5-80b7-d788329eb7a9)

**Comment by aleytus** [comment]
I found a bug on google...
If you register key at the beginning in FIDO2 and then the same key in U2F, then WebAuthn and 2FA work, but only through U2F mode
![1](https://github.com/polhenarejos/pico-fido/assets/41133651/e5ec9e2d-370a-4a7e-ad66-7d06a8d496e1)
![2](https://github.com/polhenarejos/pico-fido/assets/41133651/f4eb380b-a5c0-4791-adbd-0a3c6fc08432)

<summary>Spoiler!</summary>

**Comment by aleytus** [comment]
PS. Access to the account was restored...

**Comment by polhenarejos** [comment]
Glad to see you recover it.
Does the login through U2F work at least?

**Comment by aleytus** [comment]
I want to clarify... Were you able to reproduce the error?
The thing is that I changed the code of v2.10 firmware to suit my needs.
After I encountered the error I flashed the original latest firmware, but maybe some changes in the spi flash might have remained...

**Comment by aleytus** [comment]
I am also wondering how you debug the fido protocol. (how you intercept data for diagnostics)
I want to try to figure out the problem...

**Comment by aleytus** [comment]
"WebAuthn" Works!
The key must be created through "Security keys"

![Снимок экрана 2023-10-12 193623](https://github.com/polhenarejos/pico-fido/assets/41133651/5be4d021-54ee-4397-b5e2-e7d9a6b12437)
